# Generated by Django 4.2 on 2023-04-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('name', models.CharField(max_length=100, verbose_name='Full name develpoer')),
                ('gitLink', models.CharField(max_length=300, verbose_name='GitHub links')),
                ('work', models.CharField(max_length=100, verbose_name='Work exip')),
                ('descr', models.TextField(max_length=2000, verbose_name='Work description')),
                ('img', models.ImageField(upload_to='image/%Y', verbose_name='User img')),
            ],
        ),
    ]
